change get-psp to use the namespace selection logic

diff --git a/kubectl-get_psp b/kubectl-get_psp
--- a/kubectl-get_psp
+++ b/kubectl-get_psp
@@ -1,6 +1,34 @@
 #!/bin/bash
+NS=""
+PARAMS=""
+while (( "$#" )); do
+  case "$1" in
+    -n|--namespace)
+      NS="-n $2"
+      shift 2
+      ;;
+    -a|--all-namespaces)
+      NS="--all-namespaces"
+      shift
+      ;;
+    --) # end argument parsing
+      shift
+      break
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+      exit 1
+      ;;
+    *) # preserve positional arguments
+      PARAMS="$PARAMS $1"
+      shift
+      ;;
+  esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
 echo "NAMESPACE NAME SERVICEACCOUNT PSP STATE"
-kubectl get pod --all-namespaces -ojsonpath="{range .items[*]}ns/{@.metadata.namespace} \
+kubectl get pod $NS -ojsonpath="{range .items[*]}ns/{@.metadata.namespace} \
     pod/{@.metadata.name} sa/{@.spec.serviceAccount} \
     psp/{@.metadata.annotations['kubernetes\.io/psp']} \
     state/{@.status.phase}{@.status.containerStatuses..state..reason}{'\n'}" | column -t
